[package]
name = "proc-macro-error2"
version = "2.0.1"
edition = "2021"
rust-version = "1.99"
publish = false
license = "MIT OR Apache-2.0"
description = "Almost drop-in replacement to panics in proc-macros"
repository = "https://github.com/GnomedDev/proc-macro-error-2"

[dependencies]
quote = "1"
proc-macro2 = "1"
proc-macro-error-attr2 = "=2.0.0"
syn = { version = "2", optional = true, default-features = false }

[dev-dependencies]
syn = { version = "2", features = ["full"] }

[features]
default = ["syn-error"]
syn-error = ["dep:syn"]
nightly = []
